name: 同步包

on:
  push:
    paths:
      - ".github/workflows/package.yml"
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    name: 更新packages
    strategy:
      fail-fast: false
      matrix:
        target: [main]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 初始化环境
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: 克隆包
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x ${{matrix.target}}.sh
          git clone https://github.com/canmeng12/packages1.git ${{matrix.target}}
          cd ${{matrix.target}}
          git rm -r --cache * >/dev/null 2>&1 &
          rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
          $GITHUB_WORKSPACE/main.sh

#       - name: 补丁
#         run: |
#           find "patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d $GITHUB_WORKSPACE/${{matrix.target}} -p1 -E --forward --no-backup-if-mismatch"

      - name: 上传包
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
          [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
          cd $GITHUB_WORKSPACE/${{matrix.target}}
          git add .
          git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/canmeng12/packages1.git" HEAD:${{matrix.target}}

      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2.0.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: canmeng12/packages
          retain_days: 1
          keep_minimum_runs: 1
